### PR TITLE
Avoid using DIMs + static abstracts by using a secondary class where we hide all of the generated types.

### PR DESCRIPTION
**Pull request by jkoritzinsky**
This is an alternative to #5.

Instead of generating the implementation of `IIUnknownInterfaceType` on the user's interface directly, we create a class structure within a file-scoped class and generate two things in that file-scoped class:

1. We generate a class type that implements `IIUnknownInterfaceType` for the interface.
2. We generate an interface that derives from the parent interface and provides the DIM implementations.

The `IUnknownDerivedAttribute` will now point to these two types.

Pros of this design:

- We don't expose any API surface from the generated code to the user code.
- We don't need to provide any API stability for the API surface we generate. We have freedom to change member names or shapes in the future.
- We solve the diamond problem with IIUnknownInterfaceType.
- We avoid introducing DIMs in a derived interface, which apparently violates the API design guidelines.

Cons:

- This makes integration with the vtable generator more difficult as the outputted code shape will likely differ (instead of just needing a few conditions to be checked to ensure they can work side by side).
- We end up introducing more class types into metadata to ensure we don't have conflicts with different names (is there a technique for handling nested types/namespace names that we can take from the JSON generator?)
- It's impossible for users to use our source generator and provide a no-reflection implementation of `IIUnknownDerivedDetailsStrategy` for their use case.
  - Our implementation becomes the only one that can access code we emit, and custom implementations are basically only for integrating other source generators into our model. Users would need to write their own generator to be able to get at the interface information.
- We wouldn't be able to make the choice in #6 to optimize for our interface details strategy in nearly as effective of a manner.
  - We could only optimize looking at interface we know are COM interfaces, but we'd still need to use reflection through the attribute instead of accessing via the generic interface directly.

### CODE REVIEW

**Comment by agocke** [comment]
I'm not sure I fully understand what the attribute and generation is supposed to produce. In particular, the first implementation produces an actual implementation of `IIUnknownInterfaceType` while it looks like the second doesn't.

My question is: what is the actual impact on users of the two choices? Are users likely to want to actually pass an interface implementation directly to a method that expects `IIUnknownInterfaceType`?

In particular I'm imagining this situation:

```C#
void M1(IComInterface1 i1)
{
    M2(i1);
}

void M2(IIUnknownInterfaceType ikn) { ... }
```

In the first implementation, that should just work. In the second case, I assume you need to acquire the impl somehow? Could you ever be in a situation where it would difficult to be associate an impl with the interface? Like if you wanted to be build an abstraction that works for IComInterface1, IComInterface2, etc, that isn't based around the fact that they implement IIUnknownInterfaceType, but it might need access to that impl?

**Comment by jkoritzinsky** [comment]
The interface is meant to provide information about the COM interface type in a way that can be retrieved at a type level. For our "default" implementation, we're planning on using a generic attribute in combination with the interface to provide a trim-friendly mechanism to retrieve the information from the interface implementation.

Some users may want to provide a custom implementation of `IIUnknownInterfaceDetailsStrategy` that does not use any reflection other than `if (Type.GetTypeFromHandle(handle) == typeof(IComInterface1))`, which does not pull in any of the reflection machinery in NativeAOT but would root some information about each of the COM interfaces, reducing how much code can be trimmed. This scenario would be broken by the design in this PR as the implementations of `IIUnknownInterfaceType` would be in file-scoped classes that could not easily be referenced in a no-reflection manner.

We do not expect users to pass around instances of `IIUnknownInterfaceType`. We expect it to only be used in generic constraints for accessing the static abstract members.

**Comment by agocke** [comment]
> The interface is meant to provide information about the COM interface type in a way that can be retrieved at a type level.

I'm not quite sure what this means. What information is actually available at the type level here? That the interface has properties IID, an implementation type, and the MethodTable method? Overall it seems like at the type level you now have a proof that the interface itself can statically satisfy a COM interface. That seems valuable, but to me the primary value is achieved by actually dispatching to that interface (in most cases through a constrained generic).

However, if the actual implementation that the user would want to use is not necessarily the one attached to the interface, i.e. they don't want to directly convert the given interface to `IIUnknownInterfaceType`, the direct implementation doesn't feel particularly useful to me.

Does this help?

**Comment by jkoritzinsky** [comment]
> > The interface is meant to provide information about the COM interface type in a way that can be retrieved at a type level.
> 
> I'm not quite sure what this means. What information is actually available at the type level here? That the interface has properties IID, an implementation type, and the MethodTable method? Overall it seems like at the type level you now have a proof that the interface itself can statically satisfy a COM interface. That seems valuable, but to me the primary value is achieved by actually dispatching to that interface (in most cases through a constrained generic).

Yes, that's the information that's available.

> However, if the actual implementation that the user would want to use is not necessarily the one attached to the interface, i.e. they don't want to directly convert the given interface to `IIUnknownInterfaceType`, the direct implementation doesn't feel particularly useful to me.

Yeah we don't ever expect developers to use `IIUnknownInterfaceType` in a non-generic context, and even in a generic context we expect rare usages (that taking this approach instead of #5 would block).

> Does this help?

**Comment by agocke** [comment]
> Yes, that's the information that's available.
> 
> > However, if the actual implementation that the user would want to use is not necessarily the one attached to the interface, i.e. they don't want to directly convert the given interface to `IIUnknownInterfaceType`, the direct implementation doesn't feel particularly useful to me.
> 
Sorry, by convert here I mean "use as `IUnknownInterfaceType`, either through the interface type or constained generic." 

The question is: do people want the option to implement the interface in some other way? Or is there some reason why the default implementation is often broken? Otherwise it seems convenient to be able to just pass the value directly.

**Comment by jkoritzinsky** [comment]
> > Yes, that's the information that's available.
> > > However, if the actual implementation that the user would want to use is not necessarily the one attached to the interface, i.e. they don't want to directly convert the given interface to `IIUnknownInterfaceType`, the direct implementation doesn't feel particularly useful to me.
> 
> Sorry, by convert here I mean "use as `IUnknownInterfaceType`, either through the interface type or constained generic."
> 
> The question is: do people want the option to implement the interface in some other way? Or is there some reason why the default implementation is often broken? Otherwise it seems convenient to be able to just pass the value directly.

People can implement the interface and use the `IUnknownDerivedAttribute` to integrate their own source-generated COM systems with ours seamlessly. The design in this PR and #5 both allow this behavior.

They can also (with the current design or #5) provide their own implementation of `IIUnknownInterfaceDetailsStrategy` that consumes the interface through a constrained generic like the following:

```csharp
IIUnknownInterfaceDetails GetInterfaceDetails(RuntimeTypeHandle handle)
{
   var type  = Type.GetTypeFromTypeHandle(handle);
   if (type == typeof(IComInterface1))
   {
        return CreateInterfaceDetails<IComInterface1>();
   }

   static IIUnknownInterfaceDetails CreateInterfaceDetails<T>() where T : IUnmanagedInterfaceType
   {
       new MyCustomInterfaceDetails()
       {
             Iid = T.Iid,
             // etc.
       }
   }
}

```

The design in this PR would block the behavior in this code block, as getting from `IComInterface1` to the type to pass to `CreateInterfaceDetails<T>()` would not be possible without going through the `IUnknownDerived` attribute, which a custom implementation that does not use reflection (I'm specifically not counting `type == typeof(IComInterface1)` as reflection as the experimental reflection-disabled option in NativeAOT still supports that), would be explicitly trying to avoid.

**Comment by jkoritzinsky** [comment]
I've updated this PR with the new agreed-upon shape of how we'll emit the generated code.

**Comment by elinor-fung** [comment]
Can you also update the program to show `IComInterface4`?

**Comment by jkoritzinsky** [comment]
I'll update this branch to test IComInterface4, but I don't think it's worth fixing the identity problem since my PR for the ccw support will also fix that.

**Pull request merged**
